### PR TITLE
Major refactoring and integration with Minio

### PR DESCRIPTION
**Pull request by igormoreno**
This contains also the commits from pull requests #36
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/benchflow/data-manager/pull/37%23issuecomment-275870042%22%2C%20%22https%3A//github.com/benchflow/data-manager/pull/37%23issuecomment-276037231%22%2C%20%22https%3A//github.com/benchflow/data-manager/pull/37%23issuecomment-276037542%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/benchflow/data-manager/pull/37%23issuecomment-275870042%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22A%20think%20this%20error%20in%20the%20style%20checker%20is%20wrong%3A%5Cr%5Cn%3E%20%27%7D%27%20at%20column%209%20should%20be%20alone%20on%20a%20line.%5Cr%5Cn%60%60%60%5Cr%5Cn%7D%20while%20%28pageToken%20%21%3D%20null%29%3B%5Cr%5Cn%60%60%60%22%2C%20%22created_at%22%3A%20%222017-01-28T19%3A46%3A03Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/229440%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/igormoreno%22%7D%7D%2C%20%7B%22body%22%3A%20%22Report%20the%20wrong%20error%20to%20the%20check%20style%20community%20and%20link%20it%20here%2C%20please.%22%2C%20%22created_at%22%3A%20%222017-01-30T11%3A16%3A39Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7163641%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/VincenzoFerme%22%7D%7D%2C%20%7B%22body%22%3A%20%22This%20pull%20request%20should%20not%20contain%20the%20commits%20of%20the%20other%20pull%20request%20%28%2336%29.%20Probably%20we%20need%20to%20open%20it%20again%2C%20when%20I%20merge%20the%20%2336%20one/%22%2C%20%22created_at%22%3A%20%222017-01-30T11%3A18%3A22Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7163641%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/VincenzoFerme%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/benchflow/data-manager/pull/37#issuecomment-275870042'>General Comment</a></b>
- <a href='https://github.com/igormoreno'></a> A think this error in the style checker is wrong:
> '}' at column 9 should be alone on a line.
```
} while (pageToken != null);
```
- <a href='https://github.com/VincenzoFerme'></a> Report the wrong error to the check style community and link it here, please.
- <a href='https://github.com/VincenzoFerme'></a> This pull request should not contain the commits of the other pull request (#36). Probably we need to open it again, when I merge the #36 one/

<a href='https://www.codereviewhub.com/benchflow/data-manager/pull/37?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/benchflow/data-manager/pull/37?approve=1'></a>&nbsp;<a href='https://github.com/benchflow/data-manager/pull/37'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by VincenzoFerme** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/benchflow/data-manager/pull/37'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by igormoreno** [comment]
A think this error in the style checker is wrong:
> '}' at column 9 should be alone on a line.
```
} while (pageToken != null);
```

**Comment by VincenzoFerme** [comment]
Report the wrong error to the check style community and link it here, please.

**Comment by VincenzoFerme** [comment]
This pull request should not contain the commits of the other pull request (#36). Probably we need to open it again, when I merge the #36 one/

**Pull request closed without merging**
